[package]
name = "html-form-derive"
version = "0.1.0"
edition = "2024"
description = "Derive macros for the `html-form` crate"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "2", features = ["full", "extra-traits"] }
